apiVersion: apps/v1
kind: Deployment
metadata:
  name: leenustechs-lightroommanager-service
  namespace: default
  labels:
    app: leenustechs-lightroommanager-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leenustechs-lightroommanager-service
  template:
    metadata:
      labels:
        app: leenustechs-lightroommanager-service
    spec:
      containers:
        - name: lightroommanager
          image: hostinger.leenustechs.com.mx:5000/leenustechs-lightroommanager-service:1b71e98aa40c9c4ad84276362e7ce33926a46f67
          ports:
            - containerPort: 8084
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /lightroommanager/v1/actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /lightroommanager/v1/actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
